### PR TITLE
Light Theme (experimental)

### PR DESCRIPTION
**Pull request by flustix**
for the people who like it
(could also maybe used for custom themes, i dunno)

### CODE REVIEW

**Review by Nightcaat — APPROVED** [review]
Looks good to me. It would be nice to use [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to automatically enable the light theme if browsers report a preference for it but it is kinda jank to check for it in JS so I think this is fine for now

**Comment by GDColon** [comment]
I'll have to think about this one. I know everyone prefers their own themes but part of me wants to keep the UI consistent for everyone.

**Comment by suprstarrd** [comment]
@Nightcaat I feel like I've seen you somewhere but I don't know exactly where. That's gonna bug me for a while

I think it could work if it was like a preference of light, dark, or auto (and auto would use `prefers-color-scheme` CSS)

**Comment by Nadwey** [comment]
I'm just going to leave this here...

image
image
image

**Pull request closed without merging**
