### PR TITLE
Fixed charts being exported as [object HTMLInputElement]

### PR DESCRIPTION
**Pull request by Nadwey**

### CODE REVIEW

**Comment by GDColon** [comment]
I think it's because it's detecting the input element named chartName. Instead of renaming the variable I'll rename the element.

**Comment by Nadwey** [comment]
Yeah, but I don't see any global variable named chartName, except from this function.
Or, I'm just blind...

**Comment by GDColon** [comment]
The element named #chartName is considered a variable because javascript is stupid. I renamed it to chartNameInput

**Comment by Nadwey** [comment]
image
I think it's even more broken

**Comment by GDColon** [comment]
Refresh with ctrl+f5

**Comment by Nadwey** [comment]
Stil...
image

**Comment by GDColon** [comment]
Fixed for real, your browser uses the old saving code since it doesn't have support for the modern one.

**Pull request closed without merging**
